### ISSUE TITLE
Tiled transparency bug

### ISSUE THREAD

**Issue by ghost** [Farmerjoe12/Simple2DJavaGame#9]
When editing/creating maps in Tiled, the transparency color can be set and will work fine, but when the map is loaded via TmxMapLoader and rendered using TiledMapRenderer, the transparency color is no longer transparent.

**Comment by indivisibleman** [comment]
Adding transparency directly to the sprite sheet fixes the problem.

![transparency fix](https://cloud.githubusercontent.com/assets/708400/24513101/49e1f05a-1568-11e7-8243-a108091dc6c0.png)

**Comment by Farmerjoe12** [comment]
Can you make a pull request with the new tile sheet?
